### ISSUE TITLE
Catalogue demo for AIT team meeting on 28/03

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue-frontend#20]
Demo:
1) catalogue features (filters, columns, data types, styles) - using eLwazi catalogue - probably with snapshot json
2) demo building a new catalogue on the fly - for MICROBE version using MICROBE data from BioSamples

- [x] Jeena to outline which fields from samples to display
- [x] Wei to outline which fields to display
- [x] find a presenter - @snathanvj 
- [x] script for the demo
   1. show the current catalogue for Microbe
   2. show the configuration file
   3. add a field and a filter
   4. deploy 
   5. show the modified catalogue
   6. repeat for eLwazi   
- [x] make Microbe samples public in Prod - @ESapenaVentura 
- [ ] setup eLwazi branch
  - [ ] empty schema 
  - [ ] config file

MICROBE fields: https://miro.com/app/board/uXjVKcbsco8=/#tpicker-content

Colours for MICROBE are [here](https://drive.google.com/drive/folders/1oU0rM5-E9Ikp-Tk6Beiz9ZNRm-98OiaG)

**Comment by Jeena-Rajan** [comment]
Colours for MICROBE are [here](https://rtdservices001.sharepoint.com/sites/microbe/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fmicrobe%2FShared%20Documents%2F4%2DCommunication%5FDissemination%2F1%2DProject%20Design%20%26%20templates&viewid=c49a4be0%2D713d%2D4ec0%2Da853%2Db0a14134cd3b)

**Comment by Wkt8** [comment]
eLwazi colours are [here](https://drive.google.com/file/d/1ySWSBPc0w7h-qXrOfoeDXrJMQqcBWcXZ/view?usp=sharing)
default views of fields to display are here, but we need a column selector [eLwazi REDCap Metadata.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bad3640d16de1e888cdd62c93987afe6c49194e/eLwazi%20REDCap%20Metadata.xlsx)

**Comment by amnonkhen** [comment]
Post Demo comments
=================

1. could not deploy from Senthil's machine
2. problem connecting to biosamples prod from nginx proxy


For next demo
===========
1. rehearse sooner, not on last day
2. run all scripts from additional location (not just a single person's computer) before the demo
