### ISSUE TITLE
Multiple views in the Catalogue

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue-frontend#21]
There's a requirement from eLwazi of being able to display the metadata that is available in REDCap
There is a lot of metadata available in REDCap >> 20 fields

This can be partially solved with different views
Each project will have ONE specific category (e.g. Air Quality or Demographics) 
Would be good to have a view per category where someone filters for Demographics datasets, and demographic-specific variables are shown. 

Nice to have by April 3rd, need to have by May 1st

**Comment by Wkt8** [comment]
<img width="1240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77f0ffb73b3d0e1a10720e5702f434fd5822cf0b/Project%20Views.png" alt="Project Views.png" />

The catalogue will swap between different views - each having a default set of columns that will be shown. 
Due to the large number of potential use cases, the catalogue should also include a 'column selector' that will allow columns to be selected as preferred by the users. 

See: https://atlas.ihccglobal.org/ as an example.

**Comment by amnonkhen** [comment]
Questions:
1. What do users want to find the the eLwazi catalogue? (this way we know which views to generate)

**Comment by Wkt8** [comment]
Do we want to make different screens (e.g. a Project View, a Category View, etc.) or do as above with a Project View and a Dataset view? What are the most common use cases that we should make multiple screens for?

**Comment by Wkt8** [comment]
Essentially for now we are only going to work on the dataset view, with some quality of life fixes
