### ISSUE TITLE
MICROBE: Change CABI internal names on BioSamples submission

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue-frontend#23]
It looks like the unique internal ID on the [CABI spreadsheet](https://docs.google.com/spreadsheets/d/1yNhxkH1aYw-zzqKPzES-UrZY_EmPcu_Y/edit#gid=785907608) submission to BioSamples is the same as the [AIT ones](https://docs.google.com/spreadsheets/d/1DEyDiplmKPcid3zBqaQ08UQ6bFxly6X-/edit#gid=815956052)
The CABI names (column A on spreadsheet) on BioSamples submission spreadsheet need to be changed to the original CABI names as listed in column E (cabiname) in original [spreadsheet](https://docs.google.com/spreadsheets/d/1ZLdg76kGFlSn-D4R7ltisMdCdJz8n0_E/edit#gid=230649299) provided by CABI

**Comment by ESapenaVentura** [comment]
Overseeded by #1022
