### ISSUE TITLE
Data catalogue as a library

### ISSUE THREAD

**Issue by snathanvj** [ebi-ait/data-catalogue-frontend#34]
- [ ] build data catalogue as library and use it as a component in  different react project
- [ ] build data catalogue as library and use it as a component in different angular project
- [ ] from Sandeep: make sure the styles are easily customisable

**Comment by Wkt8** [comment]
This is for embedding the data catalogue as a whole in different environments (website, etc.)

**Comment by amnonkhen** [comment]
not needed currently.
