### ISSUE TITLE
Work with filters for dataset view for eLwazi

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue-frontend#37]
- [x] Select 'default' values in the table 
- [x] Select 'default' filters for side filters
- [x] Check that Filters function as 'or' filters when ticking values in the same field, but function as 'and' filters when ticking values in different fields 
- [x] Rearrange side filters to put project titles at the top. 

Later on: 
Dynamic filters - remove options that are no longer able to be filtered according to current filters

**Comment by Wkt8** [comment]
See Mock-up here: https://miro.com/app/board/uXjVKS4q6Tk=/

**Comment by amnonkhen** [comment]
filters per category:
<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--796f6ee8723efaadb2388db7e4d447e40a9f5599/image.png" alt="image.png" />

**Comment by amnonkhen** [comment]
@Wkt8 I need clarification please about the meaning of:

>  Select 'default' values in the table
 Select 'default' filters for side filters

**Comment by Wkt8** [comment]
[Desired Variables.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkxFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2482618a19a2bf8ee79efb050e9bc3dba6435c8/Desired%20Variables.xlsx)
