### ISSUE TITLE
basic Styling 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue-frontend#40]
Ensure that the eLwazi REACT Admin catalogue has the right colors, logos, and header names and filter names 

- [x] colours
- [x] elwazi logo
- [x] headers
- [x] filter names

Logos and colors are here: 
https://drive.google.com/drive/folders/1QYt6Dfwprqz9Jym7Ye-DQYdellSJeT4G

**Comment by amnonkhen** [comment]
Good tool to generate a 10 hue palette from a colour: https://m2.material.io/inline-tools/color/
