### ISSUE TITLE
UI changes to eLwazi catalogue

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/data-catalogue-frontend#42]
<img width="1830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--062e97f7c62f89ab5c967aa2f3636726c84df6ab/Screenshot%202024-04-26%20at%2013.19.59.png" alt="Screenshot 2024-04-26 at 13.19.59.png" />

- [ ] #49
- [x] 2. Remove the prefixes from the filter titles
- [x] 3. Hide the ID column from the catalogue
- [x] 4. Remove the prefixes and capitalise the variable names
- [ ] #50

2 and 4 might also be issues that can be fixed from the API - I can approach it from that angle if that would be better.

**Comment by amnonkhen** [comment]
**make the width of the columns adjustable** - this requires some code changes as it does not come with react admin out of the box

**Comment by amnonkhen** [comment]
The padding shown in 1 in the screen shot is not simple to fix, due to some react-admin shortcoming.

**Comment by amnonkhen** [comment]
Show issues i and 5 be moved back to the backlog?

**Comment by Jeena-Rajan** [comment]
Yes, please create tickets for issues 1 and 5 in the backlog and check with Wei next week on the necessity of these for the demo
